BEGIN
  FOR proc IN (
    SELECT object_name
    FROM user_objects
    WHERE object_type = 'PROCEDURE'
  ) LOOP
    EXECUTE IMMEDIATE 'DROP PROCEDURE ' || proc.object_name;
  END LOOP;
END;
/

BEGIN
  FOR trig IN (
    SELECT trigger_name FROM user_triggers
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TRIGGER ' || trig.trigger_name;
  END LOOP;
END;
/

BEGIN
  FOR seq IN (
    SELECT sequence_name FROM user_sequences
  ) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || seq.sequence_name;
  END LOOP;
END;
/

BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
  END LOOP;
END;
/

CREATE TABLE NHANVIEN(
    MANV CHAR(5) PRIMARY KEY,
    HOTEN NVARCHAR2(50) NOT NULL,
    PASSWORD CHAR(100) NOT NULL,
    CCCD CHAR(12) UNIQUE,
    SDT CHAR(11) UNIQUE,
    NGAYSINH DATE,
    GIOITINH CHAR(10),
    DIACHI CHAR(50),
    EMAIL CHAR(20),
    LUONG NUMBER(9),
    CHUCVU CHAR(10),
    NGAYVAOLAM DATE,
    MAQL CHAR(5)
)
/
CREATE TABLE KHACHHANG(
    MAKH CHAR(5) PRIMARY KEY,
    HOTEN NVARCHAR2(50) NOT NULL,
    PASSWORD CHAR(100) NOT NULL,
    CCCD CHAR(12) NOT NULL UNIQUE,
    SDT CHAR(11) NOT NULL UNIQUE,
    NGAYSINH DATE,
    GIOITINH CHAR(5),
    DIACHI CHAR(100),
    EMAIL CHAR(50)
)
/

CREATE TABLE PHIEUDAT (
    MAPD CHAR(5) PRIMARY KEY,
    MAKH CHAR(5),
    SLSD NUMBER(3),
    SONGUOIDUNG NUMBER(5),
    NGAYBD DATE,
    NGAYKT DATE,
    YEUCAU NVARCHAR2(100)
);
/

CREATE TABLE DVPHONG(
    MADVP CHAR(4) PRIMARY KEY,
    LOAIPHONG CHAR(50), 
    MOTA CHAR(100),
    DONGIA NUMBER(9) NOT NULL,
    TINHTRANG NVARCHAR2(100) NOT NULL
)
/

CREATE TABLE DVTIENICH(
    MADVTI CHAR(5) PRIMARY KEY,
    TENDVTI CHAR(100),
    MOTA CHAR(100),
    DONGIA NUMBER(9) NOT NULL,
    TINHTRANG NVARCHAR2(100)
)   
/

CREATE TABLE HOADON (
    MAHD CHAR(5) PRIMARY KEY,
    MAKH CHAR(5),
    NGAYTAO DATE,
    NGAYTHANHTOAN DATE,
    TINHTRANGTHANHTOAN NVARCHAR2(100),
    TONGTIEN NUMBER(9),
    SOTIENKHACHTRA NUMBER(9),
    TIENTHOI NUMBER(9),
    TINHTRANGSUDUNG NVARCHAR2(50), -- 'Chưa check in', 'Đã check in', 'Đã check out'
    NOTE NVARCHAR2(100),
    CONSTRAINT FK_HOADON_KHACHHANG FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);
/

CREATE TABLE CTHD (
    MACTHD CHAR(7) PRIMARY KEY,
    MAHD CHAR(5),
    LOAIDV CHAR(5), --'DVP' HOẶC 'DVTI'
    MADV CHAR(5),
    NGAYBD DATE,
    NGAYKT DATE,
    CONSTRAINT CTHD_HD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
);
/

--1 NHẬP DỮ LIỆU SẼ TỰ ĐỘNG NHẬP KHOÁ THEO THỨ TỰ
----------------------------------------------------------------
--NHÂN VIÊN
CREATE SEQUENCE SEQ_MANV
START WITH 1
INCREMENT BY 1
NOCACHE;
/

CREATE OR REPLACE TRIGGER AUTO_NHANVIEN
BEFORE INSERT ON NHANVIEN
FOR EACH ROW
BEGIN
    :NEW.MANV := 'NV' || LPAD(SEQ_MANV.NEXTVAL, 3, '0');
END;
/

--KHÁCH HÀNG
CREATE SEQUENCE SEQ_MAKH
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_KHACHHANG
BEFORE INSERT ON KHACHHANG
FOR EACH ROW
BEGIN
    :NEW.MAKH := 'KH' || LPAD(SEQ_MAKH.NEXTVAL, 3, '0');
END;
/

--DỊCH VỤ PHÒNG
CREATE SEQUENCE SEQ_MADVP
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_MAPHONG
BEFORE INSERT ON DVPHONG
FOR EACH ROW
BEGIN
    :NEW.MADVP := 'P' || LPAD(SEQ_MADVP.NEXTVAL, 3, '0');
END;
/

--DỊCH VỤ TIỆN ÍCH
CREATE SEQUENCE SEQ_MADVTI
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_DVTIENICH
BEFORE INSERT ON DVTIENICH
FOR EACH ROW
BEGIN
    :NEW.MADVTI := 'TI' || LPAD(SEQ_MADVTI.NEXTVAL, 3, '0');
END;
/

--PHIEUDAT
CREATE SEQUENCE SEQ_MAPD
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_PHIEUDAT
BEFORE INSERT ON PHIEUDAT
FOR EACH ROW
BEGIN
    :NEW.MAPD := 'PD' || LPAD(SEQ_MAPD.NEXTVAL, 3, '0');
END;
/

--HOÁ ĐƠN
CREATE SEQUENCE SEQ_MAHD
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_HOADON
BEFORE INSERT ON HOADON
FOR EACH ROW
BEGIN
    :NEW.MAHD := 'HD' || LPAD(SEQ_MAHD.NEXTVAL, 3, '0');
END;
/

--CHI TIẾT HOÁ ĐƠN
CREATE SEQUENCE SEQ_MACTHD
START WITH 1
INCREMENT BY 1
NOCACHE;
/
CREATE OR REPLACE TRIGGER AUTO_CTHD
BEFORE INSERT ON CTHD
FOR EACH ROW
BEGIN
    :NEW.MACTHD := 'CTHD' || LPAD(SEQ_MACTHD.NEXTVAL, 3, '0');
END;
/

--TRIGGER CTHD-------------
CREATE OR REPLACE TRIGGER LOAIDV_MADV
BEFORE INSERT OR UPDATE ON CTHD
FOR EACH ROW
DECLARE
    CHECK_MADV NUMBER(1) := 0;
BEGIN
    IF :NEW.LOAIDV = 'DVP' THEN
        SELECT 1 INTO CHECK_MADV
        FROM DVPHONG
        WHERE MADVP = :NEW.MADV;
    ELSIF :NEW.LOAIDV = 'DVTI' THEN
        SELECT 1 INTO CHECK_MADV
        FROM DVTIENICH
        WHERE MADVTI = :NEW.MADV;
    ELSE
        RAISE_APPLICATION_ERROR(-2000, 'LOAIDV INVALID!');
    END IF;
    
    IF CHECK_MADV = 0 THEN
        RAISE_APPLICATION_ERROR(-2001, 'KHONG TON TAI MADV!');
    END IF;
END;
/

-- TRIGGER HỆ THỐNG TỰ TẠO BIẾN NGAYTAO TRONG HOÁ ĐƠN
CREATE OR REPLACE TRIGGER AUTO_NGAYTAO
BEFORE INSERT ON HOADON
FOR EACH ROW
BEGIN
    :NEW.NGAYTAO := SYSDATE;
END;
/
--DVPHONG
INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng đơn', 'Phòng đơn có giường 1m6, điều hòa', 50000, N'Occupied');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng đôi', 'Phòng đôi 2 giường, có tivi và bàn làm việc', 80000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng VIP', 'Phòng VIP có ban công và bồn tắm', 15000, N'Occupied');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng gia đình', 'Phòng rộng cho 4 người, có bếp mini', 12000, N'Occupied');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng tiêu chuẩn', 'Phòng tiêu chuẩn có wifi và tủ lạnh mini', 60000, N'Occupied');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng đơn', 'Phòng đơn có cửa sổ lớn, view đẹp', 55000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng đôi', 'Phòng đôi sát biển, điều hòa trung tâm', 85000, N'Occupied');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng VIP', 'Phòng VIP có máy chiếu phim, bồn tắm lớn', 100000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng tiêu chuẩn', 'Phòng tiện nghi cơ bản, gần sảnh chính', 65000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng gia đình', 'Phòng lớn, có 2 giường đôi và khu sinh hoạt', 12000, N'Occupied');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng VIP', 'Phòng VIP có máy chiếu phim, bồn tắm lớn', 168000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng tiêu chuẩn', 'Phòng tiện nghi cơ bản, gần sảnh chính', 69000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Couple', 'Phòng VIP có máy chiếu phim, bồn tắm lớn', 23400, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Tập thể', 'Phòng tiện nghi cơ bản, gần sảnh chính', 65900, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng VIP', 'Phòng VIP có máy chiếu phim, bồn tắm lớn', 180000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng tiêu chuẩn', 'Phòng tiện nghi cơ bản, gần sảnh chính', 69000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Couple', 'Phòng VIP có máy chiếu phim, bồn tắm lớn', 234000, N'Available');

INSERT INTO DVPHONG (LOAIPHONG, MOTA, DONGIA, TINHTRANG)
VALUES ('Tập thể', 'Phòng tiện nghi cơ bản, gần sảnh chính', 1090000, N'Available');
/

--DVTIENICH
INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Giặt ủi', 'Dịch vụ giặt ủi trong ngày', 30000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Đưa đón sân bay', 'Đưa đón sân bay bằng xe 7 chỗ', 250000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Bữa sáng', 'Bữa sáng buffet tại nhà hàng', 100000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Gọi món tại phòng', 'Phục vụ đồ ăn tận phòng', 50000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Spa', 'Gói massage thư giãn 60 phút', 300000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Cho thuê xe máy', 'Thuê xe máy nguyên ngày', 120000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Phòng Gym', 'Sử dụng phòng Gym toàn thời gian', 50000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Hồ bơi', 'Sử dụng hồ bơi ngoài trời', 40000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Karaoke', 'Thuê phòng Karaoke theo giờ', 150000, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Giữ hành lý', 'Gửi hành lý miễn phí', 0, 'Available');

INSERT INTO DVTIENICH (TENDVTI, MOTA, DONGIA, TINHTRANG)
VALUES ('Nhà trẻ', 'giữ trẻ dưới 14 tuổi', 30000, 'Available');
/

--NHANVIEN
INSERT INTO NHANVIEN (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL, LUONG, CHUCVU, NGAYVAOLAM, MAQL)
VALUES (N'NHANVIEN', 'pass123', '012345678900', '0123456789', TO_DATE('1997-06-05','YYYY-MM-DD'), 'Nữ', 'Bắc Ninh', 'huong.ha@gmail.com', 14500000, 'LE TAN', TO_DATE('2023-07-15','YYYY-MM-DD'), '');
/

--KHACHHANG
INSERT INTO KHACHHANG (HOTEN, PASSWORD, CCCD, SDT, NGAYSINH, GIOITINH, DIACHI, EMAIL)
VALUES (N'KHACHHANG', 'pass123', '012345678901', '1234567890', TO_DATE('1995-03-15','YYYY-MM-DD'), 'Nữ', 'Hà Nội', 'huong.nguyen@gmail.com');
/

--HOADON
INSERT INTO HOADON (
    MAKH,
    NGAYTAO,
    NGAYTHANHTOAN,
    TINHTRANGTHANHTOAN,
    TONGTIEN,
    SOTIENKHACHTRA,
    TIENTHOI,
    TINHTRANGSUDUNG,
    NOTE
) VALUES (
    'KH001',         -- MAKH (giả sử KH001 đã tồn tại trong bảng KHACHHANG)
    SYSDATE - 2,       -- NGAYTAO
    SYSDATE - 1,       -- NGAYTHANHTOAN
    N'Đã thanh toán', -- TINHTRANGTHANHTOAN
    500000,           -- TONGTIEN
    500000,           -- SOTIENKHACHTRA
    0,                -- TIENTHOI
    N'Đã check in',     -- TINHTRANGSUDUNG
    N'Khách thanh toán đầy đủ' -- NOTE
);
/
--CTHD
-- MADVP = 'P001' tồn tại

INSERT INTO CTHD (MAHD, LOAIDV, MADV, NGAYBD, NGAYKT)
VALUES ('HD001', 'DVP', 'P001', DATE '2025-06-01', DATE '2025-06-03');

/
--MADVTI = 'TI001' tồn tại
INSERT INTO CTHD (MAHD, LOAIDV, MADV, NGAYBD, NGAYKT)
VALUES ('HD001', 'DVTI', 'TI001', DATE '2025-06-01', DATE '2025-06-03');
/

-- Tạo thêm biến Type of Service trong Phiếu Đặt 
alter table phieudat add TYPE_OF_SERVICE varchar2(1);
/

-- Tạo thêm tên service trong Phiếu Đặt
alter table phieudat add NAME_OF_SERVICE varchar2(100);
COMMIT;

-- Sửa lại trigger LOAIDV_DV
DROP TRIGGER LOAIDV_MADV;
/
CREATE OR REPLACE TRIGGER LOAIDV_MADV
BEFORE INSERT OR UPDATE ON CTHD
FOR EACH ROW
DECLARE
    CHECK_MADV NUMBER(1) := 0;
BEGIN
    IF :NEW.LOAIDV = 'DVP' THEN
        SELECT 1 INTO CHECK_MADV
        FROM DVPHONG
        WHERE MADVP = :NEW.MADV;
    ELSIF :NEW.LOAIDV = 'DVTI' THEN
        SELECT 1 INTO CHECK_MADV
        FROM DVTIENICH
        WHERE MADVTI = :NEW.MADV;
    ELSE
        RAISE_APPLICATION_ERROR(-20000, 'LOAIDV INVALID!');
    END IF;
    
    IF CHECK_MADV = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'KHONG TON TAI MADV!');
    END IF;
END;
/
